# based on a git commit sha, ideal if you need reliable and precise tracking of your code
image:
  tag: 96719781434815270429afc72b0add6f7cd56934
ingress:
  hosts:
    - host: autocicd-feat1.your-host.tld
      paths:
        - path: /
          pathType: Prefix
