name: Update environment version

on:
  workflow_call:
    inputs:
      ENV_NAME:
        description: Environment name (for file as "values-<env_name>.yaml")
        required: true
        type: string
      IMAGE_TAG:
        description: Tag of the image
        required: true
        type: string

  workflow_dispatch:
    inputs:
      ENV_NAME:
        description: Environment name (for file as "values-<env_name>.yaml")
        required: true
        type: string
      IMAGE_TAG:
        description: Tag of the image
        required: true
        type: string

jobs:
  update:
    name: Update a environment version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Setup Git
        id: setup-git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Update tag version
        id: update-and-commit
        run: |
          export TAG=${{ inputs.IMAGE_TAG }}
          export FILENAME=values-${{ inputs.ENV_NAME }}.yaml
          [[ ! -f $FILENAME ]] && exit 0

          yq e -i '.image.tag=env(TAG)' $FILENAME

          git add .
          git commit -m "Update image tag for ${{ inputs.ENV_NAME }}"
          git push

  sync:
    needs:
      - update
    uses: ArnaudTA/actions/.github/workflows/sync.yaml@main
    secrets:
      GILTAB_PROJECT_NAME: "${{ vars.GILTAB_PROJECT_NAME }}"
      GITLAB_PROJECT_ID: "${{ vars.GITLAB_PROJECT_ID }}"
      GIT_MIRROR_TOKEN: "${{ secrets.GIT_MIRROR_TOKEN }}"
      GITLAB_URL:  "${{ secrets.GITLAB_URL }}"