name: Update code on pushes and manual run

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  sync:
    uses: ArnaudTA/actions/.github/workflows/sync.yaml@main
    secrets:
      GILTAB_PROJECT_NAME: "${{ vars.GILTAB_PROJECT_NAME }}"
      GITLAB_PROJECT_ID: "${{ vars.GITLAB_PROJECT_ID }}"
      GIT_MIRROR_TOKEN: "${{ secrets.GIT_MIRROR_TOKEN }}"
      GITLAB_URL:  "${{ secrets.GITLAB_URL }}"