name: Synchronize source code

on:
  push:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Synchronize app with distant platform
    steps:
      - name: build docker image
        run: |
          curl -X POST --fail \
            -F token=${{ secrets.GIT_MIRROR_TOKEN }} \
            -F ref=main \
            -F variables[SYNC_ALL]=true \
            -F variables[PROJECT_NAME]=${{ vars.GILTAB_PROJECT_NAME }} \
            "${{ secrets.GITLAB_URL }}/api/v4/projects/${{ vars.GITLAB_PROJECT_ID }}/trigger/pipeline"
