name: Synchronize source code

on:
  workflow_call:
    secrets:
      GITLAB_URL:
        required: true
      GIT_MIRROR_TOKEN:
        required: true
      GILTAB_PROJECT_NAME:
        required: true
      GITLAB_PROJECT_ID:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Synchronize app with distant platform
    steps:
      - name: call distant pipeline for synchronisation
        run: |
          curl -X POST --fail \
            -F token=${{ secrets.GIT_MIRROR_TOKEN }} \
            -F ref=main \
            -F variables[SYNC_ALL]=true \
            -F variables[PROJECT_NAME]=${{ secrets.GILTAB_PROJECT_NAME }} \
            "${{ secrets.GITLAB_URL }}/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline"
