name: Update chart

on:
  workflow_call:
    inputs:
      ENV_NAME:
        description: Environment name (for file as "values-<env_name>.yaml")
        required: true
        type: string
      IMAGE_TAG:
        description: Tag of the image
        required: true
        type: string

  workflow_dispatch:
    inputs:
      ENV_NAME:
        description: Environment name (for file as "values-<env_name>.yaml")
        required: true
        type: string
      IMAGE_TAG:
        description: Tag of the image
        required: true
        type: string

jobs:
  update:
    name: Update a chart version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: update chart version
        id: update-chart
        run: |
          export TAG=${{ inputs.IMAGE_TAG }}
          yq e -i '.image.tag=env(TAG)' values-${{ inputs.ENV_NAME }}.yaml

          git add .
          git commit -m "Update image tag for ${{ inputs.ENV_NAME }}"
          git push

